package net.ntworld.mergeRequestIntegrationIdeEE

import net.ntworld.mergeRequestIntegrationIde.diff.DiffViewToggleCommentsActionBase

class DiffViewToggleCommentsAction : DiffViewToggleCommentsActionBase()