package net.ntworld.mergeRequestIntegrationIdeEE

import net.ntworld.mergeRequestIntegrationIde.diff.gutter.ToggleCommentsEditorActionBase

class ToggleCommentsEditorAction : ToggleCommentsEditorActionBase()