package net.ntworld.mergeRequestIntegrationIdeEE

import net.ntworld.mergeRequestIntegrationIde.diff.ToggleCommentsEditorActionBase

class ToggleCommentsEditorAction : ToggleCommentsEditorActionBase()