package net.ntworld.mergeRequestIntegration

import net.ntworld.foundation.InfrastructureProvider

class MergeRequestIntegrationInfrastructure : InfrastructureProvider() {
    private val included = listOf(
        AutoGeneratedInfrastructureProvider()
    )

    init {
        wire(this.root, this.included)
    }
}