package net.ntworld.mergeRequestIntegration

import net.ntworld.foundation.InfrastructureProvider
import net.ntworld.mergeRequest.api.ApiProvider
import net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCredentials

class MergeRequestIntegrationInfrastructure(
    providers: List<ApiProvider>
) : InfrastructureProvider() {
    private val included = listOf(
        AutoGeneratedInfrastructureProvider()
        // AutoGeneratedInfrastructureProvider(providers)
    )

    init {
        wire(this.root, this.included)
    }
}