package net.ntworld.mergeRequestIntegrationIdeCE

import net.ntworld.mergeRequestIntegrationIde.diff.DiffViewToggleCommentsActionBase

class DiffViewToggleCommentsAction : DiffViewToggleCommentsActionBase()